[package]
name = "dioxus-translate"
version = "0.1.3"
authors.workspace = true
edition.workspace = true
description = "Libraries for internalization on Dioxus"
license = "MIT"
keywords = ["dioxus", "web", "i18n", "translate"]
repository = "https://github.com/biyard/rust-sdk/tree/main/packages/dioxus-translate"

[dependencies]
dioxus-translate-macro.workspace = true
dioxus-translate-types.workspace = true
serde.workspace = true
web-sys = { version = "0.3.76", optional = true }
schemars = "0.8.21"

[features]
web = ["web-sys"]
ko = ["dioxus-translate-types/ko","dioxus-translate-macro/ko"]
