[package]
name = "api"
version = "0.7.10"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
common = { workspace = true, features = ["server"] }
serde.workspace = true
serde_json.workspace = true
slog.workspace = true
# models = { workspace = true, features = ["server"] }

bdk = { workspace = true, features = ["be"] }
by-macros = { path = "../../deps/rust-sdk/packages/by-macros" }
rest-api.workspace = true
by-axum.workspace = true
by-types.workspace = true
sqlx.workspace = true

tokio = { version = "1.40.0", features = ["full"] }
tower = "0.5.1"
chrono = "0.4.39"
uuid = { version = "1.10.1", features = ["v4"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
validator = "0.20.0"
dioxus-oauth.workspace = true

[features]
default = ["server"] 
server = []
lambda = ["bdk/lambda"]

[dev-dependencies]
rest-api.workspace = true
