[package]
name = "dioxus-popup"
version = "0.1.1"
authors.workspace = true
edition.workspace = true
description = "Library for using Popup in dioxus"
license = "MIT"
repository = "https://github.com/biyard/rust-sdk/tree/main/packages/dioxus-popup"

[dependencies]
dioxus.workspace = true
by-components.workspace = true
