[package]
name = "common"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json = { workspace = true }

chrono = "0.4.39"
base64 = "0.22.1"
ring = "0.17.8"
simple_asn1 = "0.6.2"
candid = "0.10.11"
untrusted = "0.9.0"
serde_urlencoded = "0.7.1"
num-format = "0.4.4"
validator = { version = "0.20.0", features = ["derive"] }
lazy_static = "1.5.0"
regex = "1.11.1"
gloo-net = "0.6.0"


bdk.workspace = true
sqlx = { workspace = true, optional = true }

[features]
web = ["bdk/web"]
server = ["bdk/be", "sqlx"]
