[package]
name = "rest-api"
version = "0.1.8"
edition = "2021"
description = "Library for REST API"
license = "Apache-2.0"
keywords = ["web", "rest-api"]
repository = "https://github.com/biyard/rust-sdk/tree/main/packages/rest-api"

[dependencies]
base64 = "0.22.1"
candid = "0.10.11"
chrono = "0.4.39"
reqwest.workspace = true
ring = "=0.17.8"
serde = "1.0.217"
simple_asn1 = "0.6.3"
tracing = "0.1.41"

[dev-dependencies]
tokio = { version = "1.42.0", features = ["full"] }

[features]
default=[]
web=["ring/wasm32_unknown_unknown_js"]
